name: liquid_flutter_reactive_forms
description: A companion package to liquid_flutter that provides extensions for
  reactive_forms
version: 0.0.3
homepage: https://github.com/emdgroup-liquid/liquid-flutter-reactive-forms
environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  liquid_flutter: ">=21.0.0 <23.0.0"
  reactive_forms: ">=17.0.1 <19.0.0"
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
